lexik_jwt_authentication:
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'

    token_extractors:
        # look for a token as Authorization Header
        authorization_header:
            enabled: true
            prefix:  Bearer
            name:    Authorization
        # check token in a cookie
        cookie:
            enabled: true
            name:    BEARER
